core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls'))
]

web/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='web/home.html'), name='home'),
    path('accounts/login/rediect/', views.login_redirect, name='login-redirect'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('candidates/', login_required(views.CandidateListView.as_view()), name='candidates'),
    path('candidate/<int:pk>', login_required(views.CandidateDetailView.as_view()), name='candidate-detail'),

    path('teams/', login_required(views.TeamListView.as_view()), name='teams'),
    path('team/<int:pk>', login_required(views.TeamDetailView.as_view()), name='team-detail'),

    path('activities/', login_required(views.ActivityListView.as_view()), name='activities'),

    path('activity/<int:pk>/score', login_required(views.ActivityScoreFormView.as_view()), name='activity-form'),
]

web/models.py
from django.db import models
from django.db.models import Avg, Count, OuterRef, Subquery
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    @property
    def is_mentor(self):
        return Mentor.objects.filter(user__id=self.id).exists()

    @property
    def is_candidate(self):
        return Candidate.objects.filter(user__id=self.id).exists()

    @property
    def is_admin(self):
        return Admin.objects.filter(user__id=self.id).exists()


class CandidateSet(models.QuerySet):
    def add_average_score(self):
        subquery = Candidate.objects \
            .values('id').annotate(avg=Avg('activity__activityscore__score')) \
            .filter(id=OuterRef('id'))
        return self.annotate(average_score=Subquery(subquery.values('avg')[:1]))


class Candidate(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    team = models.ForeignKey('Team', on_delete=models.SET_NULL, blank=True, null=True)

    objects = CandidateSet.as_manager()

    def __str__(self):
        return self.user.get_full_name()


class MentorSet(models.QuerySet):
    def add_num_scores(self):
        return self.annotate(num_activityscore=Count('activityscore'))

    def missing_scores(self):
        return self.add_num_scores().filter(num_activityscore__lt=Activity.objects.count())


class Mentor(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    activities = models.ManyToManyField('Activity', through='ActivityScore')

    objects = MentorSet.as_manager()

    def __str__(self):
        return str(self.user)


class Admin(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


class TeamSet(models.QuerySet):
    def add_average_score(self):
        subquery = Team.objects \
            .values('id').annotate(avg=Avg('candidate__activity__activityscore__score')) \
            .filter(id=OuterRef('id'))
        return self.annotate(average_score=Subquery(subquery.values('avg')[:1]))


class Team(models.Model):
    name = models.CharField(max_length=128, unique=True)
    mentors = models.ManyToManyField('Mentor', related_name='teams')

    objects = TeamSet.as_manager()

    def __str__(self):
        return self.name

    def __repr__(self):
        return '<%s: %s (%d)>' % (self.__class__.__name__, self.name, self.pk)


class ActivitySet(models.QuerySet):
    def add_average_score(self):
        subquery = Activity.objects \
            .values('id').annotate(avg=Avg('activityscore__score')) \
            .filter(id=OuterRef('id'))
        return self.annotate(average_score=Subquery(subquery.values('avg')[:1]))


class Activity(models.Model):
    candidate = models.ForeignKey('Candidate', on_delete=models.CASCADE)
    song_name = models.CharField(max_length=128)
    performance_date = models.DateField()
    mentors = models.ManyToManyField('Mentor', through='ActivityScore')

    class Meta:
        ordering = ['-performance_date']

    objects = ActivitySet.as_manager()

    def __str__(self):
        return self.song_name

    def __repr__(self):
        return '<%s: %s (%d)>' % (self.__class__.__name__, self.song_name, self.pk)


class ActivityScore(models.Model):
    mentor = models.ForeignKey('Mentor', on_delete=models.CASCADE)
    activity = models.ForeignKey('Activity', on_delete=models.CASCADE)
    score = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100)])

    class Meta:
        unique_together = ['mentor', 'activity']

    def __str__(self):
        return self.score

    def __repr__(self):
        return '<%s: %s (%d)>' % (self.__class__.__name__, self.score, self.pk)

web/forms.py
from django import forms

from .models import Activity, ActivityScore


class ActivityScoreForm(forms.ModelForm):
    mentor_id = forms.IntegerField(widget=forms.HiddenInput(), disabled=True)
    score = forms.IntegerField(max_value=100, min_value=0)

    class Meta:
        model = Activity
        fields = []

    def save(self, commit=True):
        activity = self.instance
        mentor_id = self.cleaned_data['mentor_id']
        score = self.cleaned_data['score']

        activityscore = activity.activityscore_set.filter(mentor_id=mentor_id).first()
        if activityscore:
            activityscore.score = score
            activityscore.save()
        else:
            ActivityScore.objects.create(activity=activity,mentor_id=mentor_id,score=score)

        return activity

web/views.py
from django.db.models import OuterRef, Subquery
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy

from .forms import ActivityScoreForm
from .models import (
    Activity,
    ActivityScore,
    Candidate,
    Mentor,
    Team
)


def login_redirect(request):
    if request.user.is_mentor:
        return redirect('candidates')
    if request.user.is_admin:
        return redirect('teams')
    return redirect('home')


class CandidateListView(generic.ListView):
    context_object_name = 'candidate_list'
    template_name = 'candidate_list.html'

    def get_queryset(self):
        queryset = Candidate.objects.add_average_score()

        if self.request.user.is_mentor:
            return queryset.filter(team__mentors__user=self.request.user)

        if self.request.user.is_admin:
            return queryset


class CandidateDetailView(generic.DetailView):
    queryset = Candidate.objects.add_average_score()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['team'] = Team.objects.add_average_score().filter(candidate=self.object).first()
        context['title'] = self.object.user.get_full_name
        return context


class TeamListView(generic.ListView):
    context_object_name = 'team_list'
    template_name = 'team_list.html'

    def get_queryset(self):
        queryset = Team.objects.add_average_score()
        if self.request.user.is_mentor:
            return queryset.filter(mentors__user=self.request.user)

        if self.request.user.is_admin:
            name_filter = self.request.GET.get('name', '')
            if name_filter:
                queryset = queryset.filter(name__contains=name_filter)
            return queryset


class TeamDetailView(generic.DetailView):
    queryset = Team.objects.add_average_score()


class ActivityListView(generic.ListView):
    context_object_name = 'activity_list'
    template_name = 'activity_list.html'

    def get_queryset(self):
        queryset = Activity.objects.add_average_score()
        if self.request.user.is_mentor:
            activityscore_qs = ActivityScore.objects \
                .filter(activity=OuterRef('id'), mentor__user=self.request.user)
            return queryset.annotate(mentor_score=Subquery(activityscore_qs.values('score')[:1]))

        if self.request.user.is_admin:
            return queryset


class ActivityScoreFormView(generic.edit.UpdateView):
    model = Activity
    template_name = 'web/activity_score_form.html'
    form_class = ActivityScoreForm
    success_url = reverse_lazy('activities')

    def get_initial(self):
        activity = self.object
        mentor = Mentor.objects.get(user=self.request.user)
        initial = { 'mentor_id': mentor.pk }
        activityscore = activity.activityscore_set.filter(mentor=mentor).first()
        if activityscore:
            initial['score'] = activityscore.score
        return initial

web/templates/web/activity_form.html
{% extends "web/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="text-center">
        <h1>{{ activity.song_name }}</h1>
        <p class="text-muted">{{ activity.candidate.user.get_full_name }}</p>
    </div>

    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

web/templates/web/activity_list.html
{% extends "web/base.html" %}

{% block content %}
    <h2>Activities</h2>
    {% if activity_list %}
        {% include "web/components/activity_table_full.html" with activities=activity_list %}
    {% else %}
        There are no activities.
    {% endif %}
{% endblock content %}

web/templates/web/activity_score_form.html
{% extends "web/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="text-center">
        <h1>{{ activity.song_name }}</h1>
        <p class="text-muted">{{ activity.candidate.user.get_full_name }}</p>
    </div>

    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

web/templates/web/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'web/vendor/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    <title>THE VOICE{% if title %} – {{ title }}{% endif %}</title>
  </head>
  <body>
    {% include "web/components/navbar.html" %}

    <main role="main" class="container">
      {% block content %}
      {% endblock content %}
    </main><!-- /.container -->

    <script src="{% static 'web/vendor/jquery/jquery-3.4.1.slim.js' %}"></script>
    <script src="{% static 'web/vendor/bootstrap/bootstrap.js' %}"></script>
  </body>
</html>

web/templates/web/candidate_detail.html
{% extends "web/base.html" %}

{% block content %}
    <h1 class="text-center">{{ candidate.user.get_full_name }}</h1>

    <div class="row">
        <div class="col-sm-4 offset-sm-4">
            {% include "web/components/cards/team_name.html" with team=team %}
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4 offset-sm-2">
            {% include "web/components/cards/candidate_score.html" with candidate=candidate %}
        </div>
        <div class="col-sm-4">
            {% include "web/components/cards/team_score.html" with team=team %}
        </div>
    </div>

    <hr />

    <h2>Activities</h2>
    {% if candidate.activity_set.count %}
        {% include "web/components/activity_table_basic.html" with activities=candidate.activity_set.add_average_score %}
    {% else %}
        There are no activities.
    {% endif %}
{% endblock content %}

web/templates/web/candidate_list.html
{% extends "web/base.html" %}

{% block content %}
    <h1>Candidates</h1>
    {% if candidate_list %}
        <div class="d-flex flex-row justify-content-around flex-wrap">
            {% include "web/components/candidate_table.html" with candidates=candidate_list show_team=True %}
    {% else %}
        <p>There are no candidates.</p>
    {% endif %}
{% endblock content %}

web/templates/web/components/activity_table.html
<table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Song Name</th>
        <th scope="col">Average Score</th>
      </tr>
    </thead>
    <tbody>
      {% for activity in activities %}
        <tr>
            <td>{{ activity.performance_date }}</td>
            <td>{{ activity.song_name }}</td>
            <td>{{ activity.average_score | floatformat:'0' | default:'N/A' }}</td>
        </tr>  
      {% endfor %}
    </tbody>
  </table>

web/templates/web/components/activity_table_basic.html
<table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Song Name</th>
        <th scope="col">Average Score</th>
      </tr>
    </thead>
    <tbody>
      {% for activity in activities %}
        <tr>
            <td>{{ activity.performance_date }}</td>
            <td>{{ activity.song_name }}</td>
            <td>{{ activity.average_score | floatformat:'0' | default:'N/A' }}</td>
        </tr>  
      {% endfor %}
    </tbody>
  </table>

web/templates/web/components/activity_table_full.html
<table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Song Name</th>
        <th scope="col">Candidate Name</th>
        <th scope="col">Average Score</th>
        {% if request.user.is_mentor %}
          <th scope="col">My Score</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for activity in activities %}
        <tr>
            <td>{{ activity.performance_date }}</td>
            <td>{{ activity.song_name }}</td>
            <td><a href="{% url 'candidate-detail' activity.candidate.pk %}">{{ activity.candidate.user.get_full_name }}</a></td>
            <td>{{ activity.average_score | floatformat:'0' | default:'N/A' }}</td>
            {% if request.user.is_mentor %}
                  <td {% if activity.mentor_score is None %}class="table-warning"{% endif %}>
                    <a href="{% url 'activity-form' activity.pk %}">{{ activity.mentor_score | default_if_none:'N/A' }}</a>
                  </td>
            {% endif %}
        </tr>  
      {% endfor %}
    </tbody>
  </table>

web/templates/web/components/candidate_card.html
<div class="card candidate__card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ candidate.user.get_full_name }}</h5>
    <p class="card-text">Average: {{ candidate.average_score | floatformat:'0' | default:'N/A' }}</p>
    <a href="{% url 'candidate-detail' candidate.pk %}" class="btn btn-primary">View</a>
  </div>
</div>

web/templates/web/components/candidate_table.html
<table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Name</th>
        {% if show_team %}
            <th scope="col">Team Name</th>
        {% endif %}
        <th scope="col">Average Score</th>
      </tr>
    </thead>
    <tbody>
      {% for candidate in candidates %}
        <tr>
            <td><a href="{% url 'candidate-detail' candidate.pk %}">{{ candidate.user.get_full_name }}</a></td>
            {% if show_team %}
                <td><a href="{% url 'team-detail' candidate.team.pk %}">{{ candidate.team.name }}</a></td>
            {% endif %}
            <td>{{ candidate.average_score | floatformat:'0' | default:'N/A' }}</td>
        </tr>  
      {% endfor %}
    </tbody>
  </table>

web/templates/web/components/cards/candidate_score.html
<div class="card text-center">
    <div class="card-body">
        <h5 class="card-title">My Average</h5>
        <p class="card-text h1">{{ candidate.average_score | floatformat:'0' | default:'N/A' }}</p>
    </div>
</div>

web/templates/web/components/cards/team_name.html
<div class="card border-light text-center">
    <div class="card-body">
        <h5 class="card-title">Team</h5>
        <p class="card-text h4"><a href="{% url 'team-detail' team.pk %}">{{ team.name }}</a></p>
    </div>
</div>

web/templates/web/components/cards/team_score.html
<div class="card text-center">
    <div class="card-body">
        <h5 class="card-title">Team Average</h5>
        <p class="card-text h1">{{ team.average_score | floatformat:'0' | default:'N/A' }}</p>
    </div>
</div>

web/templates/web/components/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
<span class="navbar-brand">THE VOICE</span>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
        {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'candidates' %}">Candidates</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'teams' %}">Teams</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'activities' %}">Activities</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
        {% endif %}
    </ul>
</div>
</nav>

web/templates/web/components/team_table.html
<table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Average Score</th>
        <th scope="col">Candidates</th>
        <th scope="col">Mentors</th>
      </tr>
    </thead>
    <tbody>
      {% for team in teams %}
        <tr>
            <td><a href="{% url 'team-detail' team.pk %}">{{ team.name }}</a></td>
            <td>{{ team.average_score | floatformat:'0' | default:'N/A' }}</td>
            <td>{{ team.candidate_set.count }}</td>
            <td>{{ team.mentors.count }}</td>
        </tr>  
      {% endfor %}
    </tbody>
  </table>

web/templates/web/home.html
{% extends "web/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <img src="{% static 'web/images/voice_logo.png' %}" width="100%">
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            {% if user.is_authenticated %}
            <div class="text-center">
                <h1>Welcome!</h1>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Your Details</h5>
                            <p class="card-text">{{ user.get_full_name }}</p>
                            <p class="card-text">{{ user.username }}</p>
                        </div>
                    </div>
            </div>
            {% else %}
                <h1 class="text-center">Login</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock content %}

web/templates/web/team_detail.html
{% extends "web/base.html" %}

{% block content %}
    <h1 class="text-center">{{ team.name }}</h1>
    <div class="row">
        <div class="col-sm-4 offset-sm-4">
            {% include "web/components/cards/team_score.html" with team=team %}
        </div>
    </div>

    <hr />

    <div class="text-center">
        <h2>Mentors</h2>
        {% if team.mentors.count %}
            {% for mentor in team.mentors.all %}
                <p>{{ mentor.user.get_full_name }}</p>
            {% endfor %}
        {% else %}
            There are no mentors.
        {% endif %}
    </div>

    <hr />

    <h2>Candidates</h2>
    {% if team.candidate_set.count %}
        {% include "web/components/candidate_table.html" with candidates=team.candidate_set.add_average_score %}
    {% else %}
        There are no candidates.
    {% endif %}
{% endblock content %}

web/templates/web/team_list.html
{% extends "web/base.html" %}

{% block content %}
    <h1>Teams</h1>
    {% if user.is_admin %}
        <form class="form-inline" method="GET">
            <div class="input-group">
                <input autofocus type="text" class="form-control" name="name" placeholder="Team" value="{{ request.GET.name }}">
            </div>
            <button type="submit" class="btn btn-primary">Filter</button>
        </form>
        <br />
    {% endif %}
    {% if team_list %}
        <div class="d-flex flex-row justify-content-around flex-wrap">
            {% include "web/components/team_table.html" with teams=team_list %}
        </div>
    {% else %}
        <p>There are no candidates.</p>
    {% endif %}
{% endblock content %}